verbose: false
instrumentation:
    compact: false
    preserve-comments: true
    excludes: ["dist/**", "vendor/**", "src/css/**", "build/**", "webpack.config.js", "src/js/storyteller.js"]
    include-all-sources: true
reporting:
    print: both
    watermarks:
        statements: [95, 97]
        lines: [95, 97]
        functions: [95, 97]
        branches: [95, 97]
check:
    global:
        branches: 95
        functions: 95
        lines: 95
        statements: 95